language: ruby
rvm:
  - 2.3.2
env:
  global:
    - RAILS_ENV=test
services:
  - sqlite3
script:
  - bundle exec rake db:schema:load --trace
  - bundle exec rspec
before_script:
  - cp config/database.yml.travis config/database.yml
