default: &default
  adapter: postgresql
  encoding: unicode
  host:     localhost
  pool: 5
  username: chatter
  password:

development:
  <<: *default
  database: chatter_development

test:
  <<: *default
  database: chatter_test

production:
  <<: *default
  database: chatter_production
